// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTypI9OaIB_x6EWluYRbMCdh9ZCPEoUWw',
    appId: '1:535661743183:web:73cf67630296ddc91cae3a',
    messagingSenderId: '535661743183',
    projectId: 'appcompostagem-d0d14',
    authDomain: 'appcompostagem-d0d14.firebaseapp.com',
    storageBucket: 'appcompostagem-d0d14.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0j4hRLVUCVX9R3xvEmW9xsF7bYYcyEEE',
    appId: '1:535661743183:android:ce9ebc3031e0b2531cae3a',
    messagingSenderId: '535661743183',
    projectId: 'appcompostagem-d0d14',
    storageBucket: 'appcompostagem-d0d14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0ZM_MTYRz_p8cR2jhz01TMwS7R7gohG4',
    appId: '1:535661743183:ios:d1a878776f938cf01cae3a',
    messagingSenderId: '535661743183',
    projectId: 'appcompostagem-d0d14',
    storageBucket: 'appcompostagem-d0d14.appspot.com',
    iosClientId: '535661743183-ed3o6f8k3f1057b482s629cm2oje7nm1.apps.googleusercontent.com',
    iosBundleId: 'com.example.appCompostagem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0ZM_MTYRz_p8cR2jhz01TMwS7R7gohG4',
    appId: '1:535661743183:ios:d1a878776f938cf01cae3a',
    messagingSenderId: '535661743183',
    projectId: 'appcompostagem-d0d14',
    storageBucket: 'appcompostagem-d0d14.appspot.com',
    iosClientId: '535661743183-ed3o6f8k3f1057b482s629cm2oje7nm1.apps.googleusercontent.com',
    iosBundleId: 'com.example.appCompostagem',
  );
}
